### ISSUE TITLE
Start Nmap-portable Error: Cannot load library libssh2.dll

### ISSUE THREAD

**Issue by xp0inter** [ryanmrestivo/Nmap-Portable#1]
Hi Ryan, 
  I download the portable file and try to run it on my Virtual Machine with the command: `nmap-portable.exe nmap -h`,  it shows the error : Cannot load library libssh2.dll. 
![image](https://user-images.githubusercontent.com/44728964/224286180-a63366ac-dc28-4706-b78d-9c2bc0c56d2c.png)

My Windows is:
Edition: Windows Server 2016 Standard
Version: 1607
OS Build 14393.447
Architecture: 64bit

How could I fix that?

**Comment by ryanmrestivo** [comment]
Hey xp0inter, I will look into this on Sunday and will let you know by then at the latest!

**Comment by ryanmrestivo** [comment]
Ok, I started looking into this - For server builds I was able to reproduce on 2016.  It appears to be an issue with how the binary is compiled, but will take me some time to figure out. 
In the meantime, I was able to get Zenmap (GUI) compiled and added it to the repository if that helps at all.

**Comment by xp0inter** [comment]
Cool, Thank you very much Ryan!

**Comment by ryanmrestivo** [comment]
Hey no problem!  I have been trying to understand what files the portable version is having trouble calling - So far I have been able to get it "working" to some degree by merging the source code files with the binary & program files.  The current working version is quite large (187MB) but I am adding it to the repository if you want to try it out.

It also seems to work better by launching 'nmap-portable.exe -V' instead of 'nmap-portable.exe nmap -V'

<img width="963" alt="nmap-portable-server-2016-poc" src="https://user-images.githubusercontent.com/53523282/225157901-ca568cba-7581-48a3-a44d-86d07cecdd51.png">

**Comment by xp0inter** [comment]
That's Great !  Thank you Ryan!
